Repository parasol-finance/application, pull requests merged in 2022-04, with the labels that each got.

#110 Improve README
  CONTRIBUTING.md
  README.md
Labels: enhancement

#111 Change application parameters for `mainnet`
  .env.example
  CONTRIBUTING.md
  README.md
Labels: enhancement, urgent, security

#107 IDO submission using Parasol SDK
  .env.example
  next.config.js
  package.json
  src/context/NftContext.tsx
  src/pages/_app.tsx
  src/pages/projects/submit.tsx
  src/pages/tiers/index.tsx
  src/styles/globals.scss
  yarn.lock
Labels: Parasol SDK, UI, IDO

#112 Finish wording
  src/pages/staking.tsx
  src/pages/tiers/index.tsx
  src/pages/tiers/migrate.tsx
  src/pages/tiers/redeem.tsx
Labels: enhancement, UI

#105 Made the responsive work in most of pages
  next.config.js
  src/components/cards/nft-card.tsx
  src/components/cards/project-card.tsx
  src/components/footer.tsx
  src/components/header.tsx
  src/components/layout.tsx
  src/components/slices/announce-bar.tsx
  src/components/slices/brands.tsx
  src/components/slices/hero.tsx
  src/components/slices/projects.tsx
  src/components/wallet-connector/WalletConnect.tsx
  src/pages/404.tsx
  src/pages/about.tsx
  src/pages/contact.tsx
  src/pages/frequently-asked-questions.tsx
  src/pages/presskit.tsx
  src/pages/profile.tsx
  src/pages/projects/[tokenAddress]/index.tsx
  src/pages/projects/index.tsx
  src/pages/projects/submit.tsx
  src/pages/staking.tsx
  src/pages/swap.tsx
  src/pages/tiers/index.tsx
  src/pages/tiers/migrate.tsx
  src/pages/tiers/redeem.tsx
  tailwind.config.js
Labels: enhancement, UI

#116 Add some github actions
  .github/workflows/eslint.yml
Labels: enhancement, ESLint

#115 Complete IDO creation
  .env.example
  next.config.js
  package.json
  src/components/editorjs.tsx
  src/context/NftContext.tsx
  src/pages/api/projects/[projectPubKey].ts
  src/pages/api/projects/index.ts
  src/pages/projects/[projectPubKey]/edit.tsx
  src/pages/projects/[projectPubKey]/index.tsx
  src/pages/projects/submit.tsx
  src/utils/functions.js
  yarn.lock
Labels: IDO

#118 Implement IDO listing
  next.config.js
  package.json
  src/components/cards/project-card.tsx
  src/components/editorjs.tsx
  src/pages/api/projects/[projectPubKey].ts
  src/pages/api/projects/index.ts
  src/pages/index.tsx
  src/pages/projects/[projectPubKey]/edit.tsx
  src/pages/projects/[projectPubKey]/index.tsx
  src/pages/projects/index.tsx
  src/pages/projects/submit.tsx
  src/utils/functions.js
  tailwind.config.js
  vercel.json
  yarn.lock
Labels: Parasol SDK, IDO

#119 Implement IDO details
  src/components/editorjs.tsx
  src/pages/projects/[projectPubKey]/index.tsx
  yarn.lock
Labels: Parasol SDK, UI, IDO

#122 Newsletter modal
  src/components/cards/project-card.tsx
  src/components/reminder-modal/ReminderModal.tsx
  src/components/reminder-modal/ReminderModalProvider.tsx
  src/components/reminder-modal/useReminderModal.tsx
  src/pages/_app.tsx
  src/pages/projects/[projectPubKey]/index.tsx
  yarn.lock
Labels: UI, IDO

#123 Complete the IDO submit page
  src/pages/projects/submit.tsx
Labels: UI, IDO

#125 Implement IDO participation page
  src/components/container.tsx
  src/components/layout.tsx
  src/pages/_app.tsx
  src/pages/about.tsx
  src/pages/projects/[projectPubKey]/index.tsx
  src/pages/projects/[projectPubKey]/participate.tsx
  src/styles/globals.scss
  tailwind.config.js
Labels: Parasol SDK, UI, IDO

#126 Implement loading state for projects card
  public/assets/preview/placeholder.png
  src/components/cards/project-card.tsx
  src/pages/projects/index.tsx
Labels: enhancement, UI

#117 Highlight the holded NFT
  src/components/cards/nft-card.tsx
  src/context/NftContext.tsx
  src/pages/tiers/index.tsx
  src/pages/tiers/redeem.tsx
Labels: enhancement, NFT, UI

#127 Redesign the NFT selector in pages
  src/pages/tiers/migrate.tsx
  src/pages/tiers/redeem.tsx
Labels: enhancement, NFT, UI

#129 Add owned NFT in the Wallet Connector
  src/components/wallet-connector/WalletConnect.tsx
  src/pages/tiers/index.tsx
  src/pages/tiers/redeem.tsx
Labels: NFT, UI

#132 Bump `parasol-finance-sdk` to `0.7.1`
  package.json
  src/pages/projects/[projectPubKey]/index.tsx
  src/pages/projects/submit.tsx
  yarn.lock
Labels: Parasol SDK

#121 Restore launchpad features
  public/assets/preview/placeholder.png
  src/components/card.tsx
  src/components/cards/project-card.tsx
  src/components/footer.tsx
  src/components/header.tsx
  src/components/slices/apply.tsx
  src/components/slices/brands.tsx
  src/components/slices/hiring.tsx
  src/components/slices/projects.tsx
  src/components/slices/team.tsx
  src/constants.ts
  src/pages/index.tsx
  src/pages/projects/[projectPubKey]/index.tsx
  src/pages/projects/index.tsx
  src/pages/tiers/index.tsx
Labels: UI, IDO

#136 Implement IDO participation page
  src/pages/projects/[projectPubKey]/participate.tsx
Labels: Parasol SDK, IDO

#138 Fix the IDO submit page
  package.json
  src/pages/projects/[projectPubKey]/index.tsx
  src/pages/projects/submit.tsx
  yarn.lock
Labels: UI, IDO

#141 Add draft section in projects listing
  package.json
  src/components/slices/projects.tsx
  src/pages/projects/[projectPubKey]/participate.tsx
  src/pages/projects/index.tsx
  yarn.lock
Labels: UI, IDO

#144 Improve responsive
  src/components/header.tsx
  src/components/slices/apply.tsx
  src/components/slices/brands.tsx
  src/components/slices/projects.tsx
Labels: enhancement, UI

#148 [Responsive] Fix contact page
  src/pages/contact.tsx
Labels: enhancement
